function CodeDefine() { 
this.def = new Array();
this.def["runModel"] = {file: "ert_main_c.html",line:64,type:"var"};
this.def["stopSem"] = {file: "ert_main_c.html",line:65,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_c.html",line:66,type:"var"};
this.def["subrateTaskSem"] = {file: "ert_main_c.html",line:73,type:"var"};
this.def["taskId"] = {file: "ert_main_c.html",line:74,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_c.html",line:75,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_c.html",line:76,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_c.html",line:77,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_c.html",line:78,type:"var"};
this.def["subRateThread"] = {file: "ert_main_c.html",line:79,type:"var"};
this.def["subratePriority"] = {file: "ert_main_c.html",line:80,type:"var"};
this.def["subrateTask"] = {file: "ert_main_c.html",line:81,type:"fcn"};
this.def["baseRateTask"] = {file: "ert_main_c.html",line:106,type:"fcn"};
this.def["exitFcn"] = {file: "ert_main_c.html",line:135,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_c.html",line:141,type:"fcn"};
this.def["px4_simulink_app_main"] = {file: "ert_main_c.html",line:170,type:"fcn"};
this.def["ekf_cf_B"] = {file: "ekf_cf_c.html",line:20,type:"var"};
this.def["ekf_cf_DW"] = {file: "ekf_cf_c.html",line:23,type:"var"};
this.def["ekf_cf_M_"] = {file: "ekf_cf_c.html",line:26,type:"var"};
this.def["ekf_cf_M"] = {file: "ekf_cf_c.html",line:27,type:"var"};
this.def["ekf_cf_SetEventsForThisBaseStep"] = {file: "ekf_cf_c.html",line:39,type:"fcn"};
this.def["rate_monotonic_scheduler"] = {file: "ekf_cf_c.html",line:53,type:"fcn"};
this.def["rt_atan2f_snf"] = {file: "ekf_cf_c.html",line:65,type:"fcn"};
this.def["ekf_cf_norm"] = {file: "ekf_cf_c.html",line:102,type:"fcn"};
this.def["ekf_cf_step0"] = {file: "ekf_cf_c.html",line:142,type:"fcn"};
this.def["ekf_cf_step1"] = {file: "ekf_cf_c.html",line:150,type:"fcn"};
this.def["ekf_cf_step"] = {file: "ekf_cf_c.html",line:923,type:"fcn"};
this.def["ekf_cf_initialize"] = {file: "ekf_cf_c.html",line:940,type:"fcn"};
this.def["ekf_cf_terminate"] = {file: "ekf_cf_c.html",line:1126,type:"fcn"};
this.def["pollfd_t"] = {file: "ekf_cf_h.html",line:65,type:"type"};
this.def["led_control_s_t"] = {file: "ekf_cf_h.html",line:66,type:"type"};
this.def["B_ekf_cf_T"] = {file: "ekf_cf_h.html",line:99,type:"type"};
this.def["DW_ekf_cf_T"] = {file: "ekf_cf_h.html",line:121,type:"type"};
this.def["ConstP_ekf_cf_T"] = {file: "ekf_cf_h.html",line:129,type:"type"};
this.def["RGBLED_MODE_ENUM"] = {file: "ekf_cf_types_h.html",line:30,type:"type"};
this.def["RGBLED_COLOR_ENUM"] = {file: "ekf_cf_types_h.html",line:47,type:"type"};
this.def["RT_MODEL_ekf_cf_T"] = {file: "ekf_cf_types_h.html",line:52,type:"type"};
this.def["ekf_cf_ConstP"] = {file: "ekf_cf_data_c.html",line:20,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:27,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:51,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:62,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:86,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:27,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:51,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:25,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:26,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:27,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:28,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:29,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:36,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:48,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:54,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:60,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:66,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:37,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:44,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:51,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:47,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:48,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:49,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:50,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:83,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:88,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:95,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:102,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:109,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:116,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:123,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:130,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:148,type:"type"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["ekf_cf_c.html"] = "../ekf_cf.c";
	this.html2Root["ekf_cf_c.html"] = "ekf_cf_c.html";
	this.html2SrcPath["ekf_cf_h.html"] = "../ekf_cf.h";
	this.html2Root["ekf_cf_h.html"] = "ekf_cf_h.html";
	this.html2SrcPath["ekf_cf_private_h.html"] = "../ekf_cf_private.h";
	this.html2Root["ekf_cf_private_h.html"] = "ekf_cf_private_h.html";
	this.html2SrcPath["ekf_cf_types_h.html"] = "../ekf_cf_types.h";
	this.html2Root["ekf_cf_types_h.html"] = "ekf_cf_types_h.html";
	this.html2SrcPath["ekf_cf_data_c.html"] = "../ekf_cf_data.c";
	this.html2Root["ekf_cf_data_c.html"] = "ekf_cf_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_defines_h.html"] = "../rt_defines.h";
	this.html2Root["rt_defines_h.html"] = "rt_defines_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","ekf_cf_c.html","ekf_cf_h.html","ekf_cf_private_h.html","ekf_cf_types_h.html","ekf_cf_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_defines_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html"];
